- name: Install editor packages
  package:
    name:
    - build-essential
    - python
    - python-dev
    - python-pip
    - python3
    - python3-dev
    - python3-pip
    - vim
    - neovim
    - silversearcher-ag
    - exuberant-ctags
  state: present
