- name: neovim
  ansible.builtin.shell: >
    curl -L -o /tmp/nvim.appimage https://github.com/neovim/neovim/releases/download/v0.6.1/nvim.appimage;
    chmod u+x /tmp/nvim.appimage;
    mv /tmp/nvim.appimage /usr/local/bin/;
    chmod a+x /usr/local/bin/nvim.appimage;
    ln -nfs /usr/local/bin/nvim.appimage /usr/local/bin/nvim;
  args:
    creates: "/usr/local/bin/nvim"
