- name: Install editor packages
  package:
    name:
    - build-essential
    - python
    - python-dev
    - python3
    - python3-dev
    - python3-pip
    - vim
    - silversearcher-ag
    - exuberant-ctags
    - ripgrep
    - fd-find
    - git 
    - curl
    - autoconf
    - libssl-dev
    state: present
