---

- hosts: all
  become: yes
  become_method: sudo
  roles:
    - base
    - editor
    - role: markosamuli.asdf
      asdf_init_shell: true
      asdf_user: "{{lookup('env', 'USER')}}"
      # TODO: How to install this: bash -c '${ASDF_DATA_DIR:=$HOME/.asdf}/plugins/nodejs/bin/import-release-team-keyring'
      asdf_plugins:
      - name: "nodejs"
        versions: ["12.16.1"]
        global: "12.20.1"
      - name: "ruby"
        versions: ["3.0.0", "2.7.2", "2.6.3"]
        global: "2.6.3"
      - name: "elixir"
        versions: ["1.11.3"]
        global: "1.11.3"
  vars:
    mysql_bind_address: '0.0.0.0'
    mysql_version: 5.7

- hosts: os_Linux
  roles:
    - utilities
    - darkwizard242.googlechrome
    - geerlingguy.docker
  vars:
    googlechrome_desired_state: latest

- hosts: os_Darwin
  roles:
    - brew
    - mac
