---

- hosts: all
  become: yes
  become_method: sudo
  roles:
    - base
    - editor
  vars:
    mysql_bind_address: '0.0.0.0'
    mysql_version: 5.7

- hosts: all #linux
  become: yes
  become_method: sudo
  roles:
    # - role: utilities
    #   when: ansible_facts['os_family'] == "Debian"
    - role: darkwizard242.googlechrome
      when: ansible_facts['os_family'] == "Debian"
  vars:
    googlechrome_desired_state: latest

- hosts: all # darwin
  become: yes
  become_method: sudo
  roles:
    - role: brew
      when: ansible_facts['os_family'] == "Darwin"
    - role: mac
      when: ansible_facts['os_family'] == "Darwin"

- hosts: all
  roles:
    - languages
