---

- hosts: all
  roles:
    - base
    - editor
    - asdf
    - db

- hosts: os_Linux
  roles:
    - utilities
    - darkwizard242.googlechrome
  vars:
    googlechrome_desired_state: latest

- hosts: os_Darwin
  roles:
    - brew
    - mac
