- name: Install required dependencies
  package:
    name: "{{ item }}"
    state: present
  loop:
    - mysql2
    - libmysqlclient-dev

- name: Add MySQL repository key
  apt_key:
    keyserver: pgp.mit.edu
    id: 5072E1F5
    state: present

- name: Add official MySQL 5.7 ubuntu focal repository
  apt_repository:
    repo: "deb http://repo.mysql.com/apt/ubuntu focal mysql-5.7"
    state: present

- name: Install MySQL dependencies
  package:
    name: "{{ item }}"
    state: present
  loop:
    - mysql-common
    - mysql-server
    - mysql-client

- name: Install Postgres dependencies
  package:
    name: "{{ item }}"
    state: present
  loop:
    - postgresql
    - postgresql-client
