---
- name: Install packages from Homebrew
  homebrew:
    state: present
    name:
      - fzf
      - jq
      - python
      - python3
      - coreutils

- name: Install Brew Cask packages
  ignore_errors: true
  homebrew_cask:
    state: present
    name:
      - alfred
      - docker
      - firefox
      - google-chrome
      - iterm2
      - licecap
      - sequel-pro
      - slack
      - spotify
      - whatsapp
